services:
  - type: web
    name: medusa-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: medusa-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: STORE_CORS
        value: /.*/
      - key: ADMIN_CORS
        value: /.*/
      - key: AUTH_CORS
        value: /.*/

  - type: redis
    name: medusa-redis
    plan: free
    ipAllowList: [] # only allow internal connections

databases:
  - name: medusa-db
    plan: free
    databaseName: medusa
    user: medusa
